name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  IMAGE_NAME: 'mywebapp'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image
      run: |
        az acr build --registry $ACR_NAME --image $IMAGE_NAME:${{ github.sha }} .

    - name: Set AKS context
      uses: azure/aks-set-context@v1
      with:
        resource-group: $RESOURCE_GROUP
        cluster-name: $AKS_CLUSTER_NAME

    - name: Deploy to AKS
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          k8s/deployment.yaml
          k8s/service.yaml
        images: |
          $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ github.sha }}
